version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
  build:
    commands:
      - echo Build started on `date`
      - mvn package spring-boot:repackage
artifacts:
  files:
    - target/demo-0.0.1-SNAPSHOT.jar
  discard-paths: yes